version: '3.1'
services:
  postgres:
    container_name: gobarber_postgres
    image: postgres
    environment:
      - POSTGRES_USER=gobarber
      - POSTGRES_PASSWORD=gobarber
      - POSTGRES_DB=gobarber
    ports:
      - '5432:5432'

  mongo:
    image: mongo
    container_name: gobarber_mongo
    ports:
      - '27017:27017'

  redis:
    container_name: gobarber_redis
    image: redis
    ports:
      - '6379:6379'
